### ISSUE TITLE
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'

### ISSUE THREAD

**Issue by pentyum** [desihub/desigal#25]
I have used pip to install desiutil, and when I use pip to install desigal, it shows:
```
(desi) username@manage:~/desihub$ git clone https://github.com/desihub/desigal
(desi) username@manage:~/desihub$ cd desigal/
(desi) username@manage:~/desihub/desigal$ pip install ./
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /home/username/desihub/desigal
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/dist.py:678: DistDeprecationWarning: use_2to3 is ignored.
        ep.load()(self, ep.name, value)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/username/desihub/desigal/setup.py", line 64, in <module>
          setup(**setup_keywords)
        File "/home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/dist.py", line 318, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/dist.py", line 354, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "/home/username/miniconda3/envs/desi/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by pentyum** [comment]
Fix the issue by modifying `'` to `"` temporally. I propose that the `desiutil `should have a more compatible method to read the version of other packages in the function of `get_version ` of `setup.py`.

**Comment by pentyum** [comment]
See https://github.com/desihub/desiutil/pull/208
